Add a check for -Bsymbolic-functions optimization

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12450,6 +12450,59 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
     CFLAGS="$OLDCFLAGS"
 
+    # See if ld supports -Bsymbolic-functions...
+    { echo "$as_me:$LINENO: checking if ld supports -Bsymbolic-functions" >&5
+echo $ECHO_N "checking if ld supports -Bsymbolic-functions... $ECHO_C" >&6; }
+    OLDLDFLAGS="$LDFLAGS"
+    LDFLAGS="$LDFLAGS -Wl,-Bsymbolic-functions"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  OLDLDFLAGS="$LDFLAGS"
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+    LDFLAGS="$OLDLDFLAGS"
+
     # See if GCC supports -fno-strict-aliasing...
     { echo "$as_me:$LINENO: checking if GCC supports -fno-strict-aliasing" >&5
 echo $ECHO_N "checking if GCC supports -fno-strict-aliasing... $ECHO_C" >&6; }
